### PR TITLE
Issue 18

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/19)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[webhooks/webhooks.go, line 226 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/19#-KYkXkac7dMmZPI1VTXN:-KYkXkadPENIMyAHS2J2:b-lfa5r6) ([raw file](https://github.com/dgraph-io/perf/blob/86392fb553df93d40c363abe5e2f614b44e6fb64/webhooks/webhooks.go#L226)):*
> ```Go
> 		return
> 	}
> 	for _, it := range incompleteTasks {
> ```

Sorry when would this happen? So if I assign a task to one person, and then assign it to another person, both would have the same name so would it delete it for the first person?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/19)*

**Comment by adishap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[webhooks/webhooks.go, line 226 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/19#-KYkXkac7dMmZPI1VTXN:-KYlOX0GZjiahOndN0_u:b2nhswy) ([raw file](https://github.com/dgraph-io/perf/blob/86392fb553df93d40c363abe5e2f614b44e6fb64/webhooks/webhooks.go#L226)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Sorry when would this happen? So if I assign a task to one person, and then assign it to another person, both would have the same name so would it delete it for the first person?
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/19)*

**Comment by pawanrawal** [comment]
Some more comments

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[webhooks/webhooks.go, line 276 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/19#-KZ-mKH_Pi-lsmrWGZND:-KZ-mKHafPewJxiZ6pka:bb3hq9d) ([raw file](https://github.com/dgraph-io/perf/blob/73d1dc956730db1b96e08b9c380f46832b5424c1/webhooks/webhooks.go#L276)):*
> ```Go
> 
> 	for _, task := range tasks {
> 		if task.Name == strings.Title(repository)+": "+i.Title {
> ```

Can we have a function which given a repo and a title, gives you the whole title called `buildTitle`

---

*[webhooks/webhooks.go, line 278 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/19#-KZ-nuEuCta5kffmOHBY:-KZ-nuEuCta5kffmOHBZ:b-kg7f1e) ([raw file](https://github.com/dgraph-io/perf/blob/73d1dc956730db1b96e08b9c380f46832b5424c1/webhooks/webhooks.go#L278)):*
> ```Go
> 		if task.Name == strings.Title(repository)+": "+i.Title {
> 			if !stringInSlice(task.Assignee, assigneeList) {
> 				// delete task from taskwarrior
> ```

Club this with the condition above. Shouldn't it be?
if taskNameMatches && stringInSlice() {
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/19#-:-KZ-o9krlYxt9UDoIofG:bs0lnh4)*

**Comment by adishap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[webhooks/webhooks.go, line 276 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/19#-KZ-mKH_Pi-lsmrWGZND:-KZ-v0lleRi2uLSdhFET:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/73d1dc956730db1b96e08b9c380f46832b5424c1/webhooks/webhooks.go#L276)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we have a function which given a repo and a title, gives you the whole title called `buildTitle`
</blockquote></details>

Done.

---

*[webhooks/webhooks.go, line 278 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/19#-KZ-nuEuCta5kffmOHBY:-KZ-v2WKzib74wqkAN_X:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/73d1dc956730db1b96e08b9c380f46832b5424c1/webhooks/webhooks.go#L278)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Club this with the condition above. Shouldn't it be?
if taskNameMatches && stringInSlice() {
}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/19)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/19#-:-KZ0IY6M2iLsXpSPsDiP:bnfp4nl)*

**Pull request merged**
