### PR TITLE
Hot fixes

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/17)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[install.sh, line 44 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz2aKgjbsuCWIPnCbe:-KXz2aKgjbsuCWIPnCbf:bojm09e) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L44)):*
> ```Shell
> cd work/src/github.com/dgraph-io/;
> 
> export GOPATH=$HOME/work;
> ```

Ideally we should write this to `~/.bashrc`.

---

*[install.sh, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz2orZ6kQ95-7tLWCe:-KXz2orZ6kQ95-7tLWCf:bgnykhv) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L47)):*
> ```Shell
> 
> #install go-sql-driver
> go get github.com/go-sql-driver/mysql;
> ```

This is a dependency of our project and should probably be vendored in using Govendor.

---

*[install.sh, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz36yLHj-3IkwceDtf:-KXz36yLHj-3IkwceDtg:bsv0fo6) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L52)):*
> ```Shell
> go get -v -u github.com/manishrjain/asanawarrior;
> 
> #install oauth2_proxy
> ```

Space after #. Also make all these echo statements.

---

*[install.sh, line 56 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz2yD2t8ZuFktC8CFi:-KXz2yD3_JoOuu-RpZWh:b-smjhaa) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L56)):*
> ```Shell
> 
> #install sendgrid-go
> go get github.com/sendgrid/sendgrid-go;
> ```

Dependency should be vendored in

---

*[install.sh, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz30W35_zwkWUCKa_m:-KXz30W35_zwkWUCKa_n:bzdaezh) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L65)):*
> ```Shell
> sudo apt-get install nginx;
> 
> git clone https://github.com/dgraph-io/perf;
> ```

Do a go get. Add a new line.

---

*[main.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz3HKbVEHQueki_sMa:-KXz3HKbVEHQueki_sMb:bgf7jek) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/main.go#L91)):*
> ```Go
> 			}
> 			// take backup of database
> 			cmd := "mysqldump -u root -p'root' perf_db > db_backup.sql"
> ```

Don't hardcode username password. They should be flags. Also don't overwrite previous day's file. The file should have date time as part of its name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17)*

**Comment by adishap** [comment]
Review status: 2 of 53 files reviewed at latest revision, 6 unresolved discussions.

---

*[install.sh, line 44 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz2aKgjbsuCWIPnCbe:-KY1ziooymFUz74coUa1:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L44)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Ideally we should write this to `~/.bashrc`.
</blockquote></details>

Done.

---

*[install.sh, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz2orZ6kQ95-7tLWCe:-KY21pZOnuu_V-WPv53D:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L47)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This is a dependency of our project and should probably be vendored in using Govendor.
</blockquote></details>

Done.

---

*[install.sh, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz36yLHj-3IkwceDtf:-KY1zuR9DI_QJjcV6c2H:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L52)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Space after #. Also make all these echo statements.
</blockquote></details>

Done.

---

*[install.sh, line 56 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz2yD2t8ZuFktC8CFi:-KY2-vdqSHyOb17gn6W8:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L56)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Dependency should be vendored in
</blockquote></details>

Done.

---

*[install.sh, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz30W35_zwkWUCKa_m:-KY2-3UNwtYQ7RGLEp4B:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/install.sh#L65)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Do a go get. Add a new line.
</blockquote></details>

Done.

---

*[main.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KXz3HKbVEHQueki_sMa:-KY2Mb9DQcg3Sn_JdYGn:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/6bd5d8357d4e11b20de8d78da3a7487f05cabec9/main.go#L91)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't hardcode username password. They should be flags. Also don't overwrite previous day's file. The file should have date time as part of its name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17)*

**Comment by pawanrawal** [comment]
some more comments apart from that :lgtm: 

---

Review status: 2 of 53 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 93 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYLjqR8AG3Un5Ucwe2D:-KYLjqR8-ywdAaFFIEFY:b-7atbvh) ([raw file](https://github.com/dgraph-io/perf/blob/a51da40138eba4fba5f218d2e84224514cc8ba37/main.go#L93)):*
> ```Go
> 
> 			// take backup of database
> 			dsnString := *scores.DsnString
> ```

Get the index first, if its -1 print an error and return. Else proceed to find the username, password.
Because if its -1, this could would break.

---

*[main.go, line 96 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYLkex77gZnWm423zkd:-KYLkex79MjRhONhZeq-:b-jce9j5) ([raw file](https://github.com/dgraph-io/perf/blob/a51da40138eba4fba5f218d2e84224514cc8ba37/main.go#L96)):*
> ```Go
> 			username := dsnString[:strings.Index(dsnString, ":")]
> 			password := dsnString[strings.Index(dsnString, ":")+1 : strings.Index(dsnString, "@")]
> 			cmd := "mkdir -p databaseBackup && mysqldump -u " + username + " -p'" + password + "' perf_db > databaseBackup/$(date +'%Y%m%d').db.sql"
> ```

Try using sprintf, it looks cleaner.

---

*[README.md, line 46 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYLl0Ny1wUYdS_M5N3j:-KYLl0NyEv51d3MZ6m1-:b-9k13) ([raw file](https://github.com/dgraph-io/perf/blob/a51da40138eba4fba5f218d2e84224514cc8ba37/README.md#L46)):*
> ```Markdown
> 5. For perf system, go to [http://localhost](http://localhost)
> 
> ### For linux based system, installation can also be done using automation script.
> ```

Actually just change the Install section to say that installation can be done using install.sh script because thats all we need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17#-:-KYLlZt3DtZqZVX4xiUd:b-ky72ub)*

**Comment by adishap** [comment]
Review status: 2 of 53 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 93 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYLjqR8AG3Un5Ucwe2D:-KYMfcxw5hoDE2S9Hu10:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a51da40138eba4fba5f218d2e84224514cc8ba37/main.go#L93)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Get the index first, if its -1 print an error and return. Else proceed to find the username, password.
Because if its -1, this could would break.
</blockquote></details>

Done.

---

*[main.go, line 96 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYLkex77gZnWm423zkd:-KYMgdwS50eIrRNz-UwB:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a51da40138eba4fba5f218d2e84224514cc8ba37/main.go#L96)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Try using sprintf, it looks cleaner.
</blockquote></details>

Done.

---

*[README.md, line 46 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYLl0Ny1wUYdS_M5N3j:-KYMiDg-5bf8skSEAk2i:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a51da40138eba4fba5f218d2e84224514cc8ba37/README.md#L46)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Actually just change the Install section to say that installation can be done using install.sh script because thats all we need.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17)*

**Comment by pawanrawal** [comment]
Review status: 2 of 53 files reviewed at latest revision, 4 unresolved discussions.

---

*[main.go, line 76 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkYJSRkjgj54xAeW8W:-KYkYJSRkjgj54xAeW8X:b-2a5vu6) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/main.go#L76)):*
> ```Go
> func updateDatabase() {
> 	interval := 5 * time.Second
> 	ticker := time.NewTicker(interval)
> ```

Something unrelated, we should get the perf mail at 9 AM sydney time on Friday. Can you please change it to that.

---

*[main.go, line 76 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkeW5_fSkbDiCaILtT:-KYkeW5_fSkbDiCaILtU:b-bgvpd5) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/main.go#L76)):*
> ```Go
> func updateDatabase() {
> 	interval := 5 * time.Second
> 	ticker := time.NewTicker(interval)
> ```

I am thinking would it be cleaner if we could update the ticker in one loop and have the actual logic in a loop after that. That way we can avoid the if condition below? Think about it.

---

*[main.go, line 97 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkekHxT35Cf_9dQJOd:-KYkekHxT35Cf_9dQJOe:b-mdh3oa) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/main.go#L97)):*
> ```Go
> 			atIndex := strings.Index(dsnString, "@")
> 
> 			if colonIndex != -1 && atIndex != -1 {
> ```

if colonIndex == -1 || atIndex == -1 {
log.Println()
continue
}
// rest of the logic here.

This would read better.

---

*[vendor/vendor.json, line 25 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkf32oqE2oRhfXo2Ld:-KYkf32oqE2oRhfXo2Le:b-8epsqu) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/vendor/vendor.json#L25)):*
> ```JSON
> 		{
> 			"checksumSHA1": "ynJSWoF6v+3zMnh9R0QmmG6iGV8=",
> 			"path": "github.com/pkg/errors",
> ```

Where are you using this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17)*

**Comment by adishap** [comment]
Review status: 2 of 53 files reviewed at latest revision, 4 unresolved discussions.

---

*[main.go, line 76 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkYJSRkjgj54xAeW8W:-KYq9coyvlTEvc34fzs6:bb6un1j) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/main.go#L76)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Something unrelated, we should get the perf mail at 9 AM sydney time on Friday. Can you please change it to that.
</blockquote></details>

Done

---

*[main.go, line 76 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkeW5_fSkbDiCaILtT:-KYq9eVHqe-D0lQGg6zz:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/main.go#L76)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I am thinking would it be cleaner if we could update the ticker in one loop and have the actual logic in a loop after that. That way we can avoid the if condition below? Think about it.
</blockquote></details>

Done.

---

*[main.go, line 97 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkekHxT35Cf_9dQJOd:-KYlPw3iwtbSmg4Q9cE1:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/main.go#L97)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

if colonIndex == -1 || atIndex == -1 {
log.Println()
continue
}
// rest of the logic here.

This would read better.
</blockquote></details>

Done.

---

*[vendor/vendor.json, line 25 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/17#-KYkf32oqE2oRhfXo2Ld:-KYlRa-SQjLqOP3scU29:b-e1xicj) ([raw file](https://github.com/dgraph-io/perf/blob/f1aa440695106f76cee943e728486b9bcbb1ef7f/vendor/vendor.json#L25)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Where are you using this?
</blockquote></details>

I use this to create errors like "Username not available", "Invalid users", etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17)*

**Comment by pawanrawal** [comment]
:lgtm: 

---

Review status: 1 of 53 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/17#-:-KYqNNEOkkYZZd267mMN:bg7igkv)*

**Pull request merged**
