### PR TITLE
Feature email

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/13)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[main.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAbRNFab9VMwK2XULn:-KXAbRNFab9VMwK2XULo:b-svtwip) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/main.go#L110)):*
> ```Go
> 
> func weeklyReport() {
> 	interval := 5 * time.Second
> ```

maybe have this as one hour, I understand this only happens on the first day.

---

*[main.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAbExtTs0QQ_4zxFMT:-KXAbExtTs0QQ_4zxFMU:b8uc0ao) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/main.go#L116)):*
> ```Go
> 	}
> 	updateTime := time.Date(time.Now().Year(), time.Now().Month(), time.Now().Day(), 23, 0, 0, 0, IST)
> 	ticker := time.NewTicker(interval)
> ```

I think we are reusing this stuff above this line at three places, good opportunity to abstract this into a function.
Maybe read whats wrong with the top upvoted problem here and avoid that
http://stackoverflow.com/questions/19549199/golang-implementing-a-cron-executing-tasks-at-a-specific-time/39295990#39295990

---

*[main.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAb28ebyI-LmWmU7oe:-KXAb28ebyI-LmWmU7of:b5wuel5) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/main.go#L150)):*
> ```Go
> 	go updateDatabase()
> 
> 	//set timer to check performance of user every alternate day at 11 PM daily
> ```

space after // here and below.

---

*[email/email.go, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAcG8Ys_i4ulqtk_hI:-KXAcG8Ys_i4ulqtk_hJ:b-si3ihb) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L17)):*
> ```Go
> 
> var (
> 	sendgridToken = flag.String("sendgridToken", "", "Sendgrid token to send Emails")
> ```

I think you can just call the flag sendgrid because the description already tells what it is. Also its sendgrid API key to be precise.

---

*[email/email.go, line 21 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAcweRYta-A8XIN4gd:-KXAcweRYta-A8XIN4ge:b-4kxlms) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L21)):*
> ```Go
> 
> func getUserEmail(user string) (string, error) {
> 	for i := range webhooks.Users {
> ```

Is this coming from the config file?

---

*[email/email.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAcUy62Ot2um9sObgt:-KXAcUy62Ot2um9sObgu:b-7dslme) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L57)):*
> ```Go
> 	to := mail.NewEmail(user, email)
> 	content := mail.NewContent("text/html", body)
> 	from := mail.NewEmail("Adisha Porwal", "porwaladisha@gmail.com")
> ```

Send it from Perf, perf@dgraph.io.

---

*[email/email.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAd3rZtoMp2xzMOA0l:-KXAd3rZtoMp2xzMOA0m:bkydz6e) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L107)):*
> ```Go
>     <style>
>     table{
>     	width:100%;
> ```

Hmm, have template files for all this html. Don't inline them. I am doing this in Gru but its bad practice.

---

*[email/email.go, line 149 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAdAg5KNhLJj48L4Mo:-KXAdAg5KNhLJj48L4Mp:b-dv9brb) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L149)):*
> ```Go
> 	</table>
> 	<br/><br/>
> 	For more details visit <a href="perf.dgraph.io">Perf</a>. 
> ```

https://perf.dgraph.io

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/13)*

**Comment by adishap** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[main.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAbRNFab9VMwK2XULn:-KXFlWaJcOaAmLmZH3fo:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/main.go#L110)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> maybe have this as one hour, I understand this only happens on the first day.
</details>
Done.

---

*[main.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAbExtTs0QQ_4zxFMT:-KXJVZsct_rKW5lKycE2:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/main.go#L116)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I think we are reusing this stuff above this line at three places, good opportunity to abstract this into a function.
> Maybe read whats wrong with the top upvoted problem here and avoid that
> http://stackoverflow.com/questions/19549199/golang-implementing-a-cron-executing-tasks-at-a-specific-time/39295990#39295990
</details>
Done.

---

*[main.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAb28ebyI-LmWmU7oe:-KXFlbZEuuQDrfcVHDx0:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/main.go#L150)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> space after // here and below.
</details>
Done.

---

*[email/email.go, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAcG8Ys_i4ulqtk_hI:-KXFle2zUxEnSV6m_ZNs:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L17)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I think you can just call the flag sendgrid because the description already tells what it is. Also its sendgrid API key to be precise.
</details>
Done.

---

*[email/email.go, line 21 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAcweRYta-A8XIN4gd:-KXFljaYMFxVPqx9-JLj:b2nign6) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L21)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Is this coming from the config file?
</details>
yes

---

*[email/email.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAcUy62Ot2um9sObgt:-KXFllZeMdmIHJblOsi8:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L57)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Send it from Perf, perf@dgraph.io.
</details>
Done.

---

*[email/email.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAd3rZtoMp2xzMOA0l:-KXOySt3X7K_echoTp3d:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L107)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, have template files for all this html. Don't inline them. I am doing this in Gru but its bad practice.
</details>
Done.

---

*[email/email.go, line 149 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAdAg5KNhLJj48L4Mo:-KXFm0vreFJaFVSN3C_l:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L149)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> https://perf.dgraph.io
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/13)*

**Comment by pawanrawal** [comment]
A couple of small things, apart from that :lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[email/email.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAd3rZtoMp2xzMOA0l:-KXPWf0nfbnbjpgyw2yq:bpthecb) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L107)):*
<details><summary><i>Previously, adishap (Adisha Porwal) wrote…</i></summary>
> Done.
</details>
Add a TODO to move them to template files.

---

*[email/email.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXPWjiaTUYdiL2g1FXY:-KXPWjibbeG4BFAap9d5:b-co96ky) ([raw file](https://github.com/dgraph-io/perf/blob/7ec4df7207fb59bce2d6b1e2aadffa1f418b9c4c/email/email.go#L111)):*
> ```Go
> 	to := mail.NewEmail(user, email)
> 	content := mail.NewContent("text/html", body)
> 	from := mail.NewEmail("Perf System", "perf@gdgraph.io")
> ```

Also, CC yourself. So that you can check the system in the first few days. Later you can remove the CC. 
https://github.com/dgraph-io/gru/blob/develop/admin/mail/mail.go#L95 this is how you CC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/13#-:-KXPX57N7N1jxbDjDq4o:b-9277yy)*

**Comment by adishap** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[email/email.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXAd3rZtoMp2xzMOA0l:-KXPcitZWkCCKLv75iw5:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/bed0324a24c2a6f7b20dd40d016988e6a01c32ec/email/email.go#L107)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Add a TODO to move them to template files.
</details>
Done.

---

*[email/email.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/13#-KXPWjiaTUYdiL2g1FXY:-KXPcfvMidd_HRg42ZO5:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/7ec4df7207fb59bce2d6b1e2aadffa1f418b9c4c/email/email.go#L111)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Also, CC yourself. So that you can check the system in the first few days. Later you can remove the CC. 
> https://github.com/dgraph-io/gru/blob/develop/admin/mail/mail.go#L95 this is how you CC.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/13)*

**Pull request merged**
