### PR TITLE
Feature/vacation ui

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/11)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Reviewed 6 of 12 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 28 unresolved discussions.

---

*[main.go, line 28 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXbbODAgHov5OleRod:-KWXbbOE-mEAdyFShJKf:b-1w0wmp) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/main.go#L28)):*
> ```Go
> 	"github.com/dgraph-io/perf/dashboard"
> 	"github.com/dgraph-io/perf/scores"
> 	"github.com/dgraph-io/perf/vacationLog"
> ```

why not just call it vacations? I think camelcase isn't the convention for package names.

---

*[main.go, line 37 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXbmfpKWbKdEgya-4d:-KWXbmfpKWbKdEgya-4e:be0nk9h) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/main.go#L37)):*
> ```Go
> 	http.HandleFunc("/payload", webhooks.PayloadHandler)
> 	// vacation
> 	http.HandleFunc("/vacation", vacationLog.VacationLog)
> ```

vacations.Index

---

*[main.go, line 38 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXbp7z_lzDmVrrNgUy:-KWXbp7z_lzDmVrrNgUz:bdya41k) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/main.go#L38)):*
> ```Go
> 	// vacation
> 	http.HandleFunc("/vacation", vacationLog.VacationLog)
> 	http.HandleFunc("/vacation/editVacation", vacationLog.EditVacation)
> ```

vacations.Edit?

---

*[scores/scores.go, line 469 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXe0XHANf5E6n9Qddi:-KWXe0XIsRlVbDL3T1AV:b1l4xj3) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/scores/scores.go#L469)):*
> ```Go
> 
> // CalculatePresence is get presence factor of user from vacation log
> func CalculatePresence(users []string) (map[string]float64, error) {
> ```

This function should take num of days into account, because on user dashboard you display scores based on number of days. That score should take vacations into account.

---

*[scores/scores.go, line 477 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXdiBAr8jic97hV0LJ:-KWXdiBAr8jic97hV0LK:bxpxz47) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/scores/scores.go#L477)):*
> ```Go
> 	pfMap := make(map[string]float64)
> 
> 	for user := range vl {
> ```

This could be made simpler, what we want to get is the ratio of the number of days the user was in office vs the number of working days. I don't understand why we have this s := 10 below.

---

*[vacationLog/vacationLog.go, line 1 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXc4uXSmBQHkanoHNp:-KWXc4uYxPfjXb9pm6PN:bjhixuc) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L1)):*
> ```Go
> /*
> ```

can just be called vacation.go

---

*[vacationLog/vacationLog.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcK4jg4WtmMVmLumv:-KWXcK4kNCknFZDBOOgY:b-cru098) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L35)):*
> ```Go
> // VacationLog parses scores.html to /score url
> func VacationLog(w http.ResponseWriter, r *http.Request) {
> 	if r.Method == "GET" {
> ```

What are we doing here based on the method of the request?

---

*[vacationLog/vacationLog.go, line 105 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcbiSog8LMmQ7G4c8:-KWXcbiSog8LMmQ7G4c9:b-52u3vl) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L105)):*
> ```Go
> 	from := r.FormValue("from")
> 	id := r.FormValue("id")
> 	toDate, _ := time.Parse("01/02/2006", to)
> ```

you might want to use the constant here?

---

*[vacationLog/vacationLog.go, line 106 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcfycZGiikA6NgV8Q:-KWXcfycZGiikA6NgV8R:bnv75u7) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L106)):*
> ```Go
> 	id := r.FormValue("id")
> 	toDate, _ := time.Parse("01/02/2006", to)
> 	fromDate, _ := time.Parse("01/02/2006", from)
> ```

why aren't we handling errors?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/11)*

**Comment by adishap** [comment]
Review status: 9 of 13 files reviewed at latest revision, 28 unresolved discussions.

---

*[main.go, line 28 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXbbODAgHov5OleRod:-KWXhyeQzn-r_yaoeq-b:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/main.go#L28)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> why not just call it vacations? I think camelcase isn't the convention for package names.
</details>
Done.

---

*[main.go, line 37 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXbmfpKWbKdEgya-4d:-KWXegWb6ayEVZ6iiKdy:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/main.go#L37)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> vacations.Index
</details>
Done.

---

*[main.go, line 38 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXbp7z_lzDmVrrNgUy:-KWXeiIKAztCfJwALX8_:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/main.go#L38)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> vacations.Edit?
</details>
Done.

---

*[app/assets/js/vacation.js, line 124 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fq-r1-124:-KWa5v-0X7MifnMm8kEK:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/app/assets/js/vacation.js#L124)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> Missing semicolon.
</details>
Done.

---

*[app/assets/js/vacation.js, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fq-r1-125:-KWa5vaTmkcqwPmU-Twk:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/app/assets/js/vacation.js#L125)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> Missing semicolon.
</details>
Done.

---

*[scores/scores.go, line 469 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXe0XHANf5E6n9Qddi:-KWXf0__1-0w5cTARp3B:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/scores/scores.go#L469)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This function should take num of days into account, because on user dashboard you display scores based on number of days. That score should take vacations into account.
</details>
Done.

---

*[scores/scores.go, line 477 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXdiBAr8jic97hV0LJ:-KWa5qTtRl5ZAL6YDv53:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/scores/scores.go#L477)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This could be made simpler, what we want to get is the ratio of the number of days the user was in office vs the number of working days. I don't understand why we have this s := 10 below.
</details>
Done.

---

*[webhooks/webhooks.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fz-r1-97:-KWXghlPpwu_UjV-uG_Q:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/webhooks/webhooks.go#L97)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported type Tasks should be of the form "Tasks ..." (with optional leading article)
</details>
Done.

---

*[vacationLog/vacationLog.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fy-r1-47:-KWXfgyCujU_c--f0rBx:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/vacationLog/vacationLog.go#L47)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use underscores in Go names; var to_date should be toDate
</details>
Done.

---

*[vacationLog/vacationLog.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fy-r1-48:-KWXfhds5xrDIorne6NL:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/vacationLog/vacationLog.go#L48)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use underscores in Go names; var from_date should be fromDate
</details>
Done.

---

*[vacationLog/vacationLog.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fy-r1-97:-KWXgE4_LTM2MsSNf8xx:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/vacationLog/vacationLog.go#L97)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported function EditVacation should be of the form "EditVacation ..."
</details>
Done.

---

*[vacationLog/vacationLog.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fy-r1-107:-KWXgamHVPrLx5FbpLj9:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/vacationLog/vacationLog.go#L107)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use underscores in Go names; var to_date should be toDate
</details>
Done.

---

*[vacationLog/vacationLog.go, line 108 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fy-r1-108:-KWXgZhDS_VSXAZqIWT_:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/vacationLog/vacationLog.go#L108)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use underscores in Go names; var from_date should be fromDate
</details>
Done.

---

*[vacationLog/vacationLog.go, line 138 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWWrerermdy3anfO2fy-r1-138:-KWXgfg5Zk2bSrghs4Dy:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/5727a2786176854642112bd373e169799410a03b/vacationLog/vacationLog.go#L138)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported func GetVacations returns unexported type []vacationLog.vacation, which can be annoying to use
</details>
Done.

---

*[vacationLog/vacationLog.go, line 1 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXc4uXSmBQHkanoHNp:-KWXfDVS9557tgmcQs1t:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L1)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> can just be called vacation.go
</details>
Done.

---

*[vacationLog/vacationLog.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcK4jg4WtmMVmLumv:-KWXfuzQV8GBwcgnjsin:b-xiqtr9) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L35)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> What are we doing here based on the method of the request?
</details>
If the method is GET it will render vacation template else on form submission it should handle the form

---

*[vacationLog/vacationLog.go, line 105 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcbiSog8LMmQ7G4c8:-KWXgdDYQXPzZSZUmWz-:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L105)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> you might want to use the constant here?
</details>
Done.

---

*[vacationLog/vacationLog.go, line 106 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcfycZGiikA6NgV8Q:-KWXgZBaxJ5mBEOFvitL:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacationLog/vacationLog.go#L106)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> why aren't we handling errors?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/11)*

**Comment by pawanrawal** [comment]
So I hope the score calculation on the user dashboard now takes into account vacations for the past 15/30 days and so on? :lgtm: 

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[main.go, line 39 at r4](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWbk35KMi5cKGez4rn_:-KWbk35KMi5cKGez4rna:b-d2ij3r) ([raw file](https://github.com/dgraph-io/perf/blob/7f1afce960ab3920b9967411a8dda5f36a3e0470/main.go#L39)):*
> ```Go
> 	http.HandleFunc("/vacation", vacation.Index)
> 	http.HandleFunc("/vacation/editVacation", vacation.Edit)
> 	http.HandleFunc("/vacation/displayVacations", vacation.ShowVacations)
> ```

vacation.Show? 
The idea is that package names already tell you something so not point in repeating that information.

---

*[vacation/vacation.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcK4jg4WtmMVmLumv:-KWbkM-eM0Gfcdas9jrV:b-i4rmkh) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacation/vacation.go#L35)):*
<details><summary><i>Previously, adishap (Adisha Porwal) wrote…</i></summary>
> If the method is GET it will render vacation template else on form submission it should handle the form
</details>
Hmm, would be better to break this into different functions with different endpoints. 
One would be GET /index, other should be
POST /vacation

Read about RESTful routes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/11#-:-KWbkd5TX2za7LE-Pkc_:bil6b2)*

**Comment by adishap** [comment]
Yes

---

Review status: 9 of 13 files reviewed at latest revision, 22 unresolved discussions.

---

*[main.go, line 39 at r4](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWbk35KMi5cKGez4rn_:-KWbqusMpoPHpgO_SKi6:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/7f1afce960ab3920b9967411a8dda5f36a3e0470/main.go#L39)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> vacation.Show? 
> The idea is that package names already tell you something so not point in repeating that information.
</details>
Done.

---

*[vacation/vacation.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/11#-KWXcK4jg4WtmMVmLumv:-KWbscoz8PjDhCXI1CLw:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3b7518a85f512f529113fafbb3a6c03df86c33fc/vacation/vacation.go#L35)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, would be better to break this into different functions with different endpoints. 
> One would be GET /index, other should be
> POST /vacation
> 
> Read about RESTful routes.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/11#-:-KWbr32JMWoEGQ4_jKWz:bb77ueg)*

**Pull request closed without merging**
