### PR TITLE
Solve multiple task creation error

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/12)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[webhooks/webhooks.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5dA9Q18wmRmQijKrZ:-KX5dA9Q18wmRmQijKr_:bmxo4r2) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L35)):*
> ```Go
> 	apiBaseURL  = "https://app.asana.com/api/1.0"
> 	projectID   = 207298353998296
> 	workspaceID = 90967608774493
> ```

we didn't make these as flags?

---

*[webhooks/webhooks.go, line 45 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5dKVFyselTEiJsvAC:-KX5dKVFyselTEiJsvAD:bt30z09) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L45)):*
> ```Go
> }
> 
> type assigneeTasksMap struct {
> ```

so you don't need encapsulation for this. 
```
var (
mu sync.Mutex
assigneeMap map[int][]string
)
It is obvious when you declare it like this that mu guards assigneeMap.
```


---

*[webhooks/webhooks.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5dTkd_IcwZrYpxARI:-KX5dTkd_IcwZrYpxARJ:bxqkqe9) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L47)):*
> ```Go
> type assigneeTasksMap struct {
> 	sync.Mutex
> 	task map[int][]string
> ```

Have a comment here that this contains PR no => assignees information.

---

*[webhooks/webhooks.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5e1ugQ86nK-TnyQtC:-KX5e1ugQ86nK-TnyQtD:bx42frz) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L71)):*
> ```Go
> 		log.Fatal(err)
> 	}
> 	assigneeTasks.task = map[int][]string{}
> ```

can just be assigneeMap = make(map[]int[]string)

---

*[webhooks/webhooks.go, line 278 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5edo2sLB0QXoLxceF:-KX5edo2sLB0QXoLxceG:bqfna56) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L278)):*
> ```Go
> 		}
> 		for _, a := range pr.Assignees {
> 			if aList[a.Login] {
> ```

what is `a.Login`?

---

*[webhooks/webhooks.go, line 284 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5ffOe8Xhc-nVc39Im:-KX5ffOfqGAueLsoxMmB:b-7zs2f2) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L284)):*
> ```Go
> 			tasksMap[pr.Number] = append(tasksMap[pr.Number], a.Login)
> 
> 			t.Name = "Review PR on " + pr.Title
> ```

Move some of this to another function.
func newTask() *Task {
}

---

*[webhooks/webhooks.go, line 300 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5f5OCQMMGyUkcjBpn:-KX5f5OCQMMGyUkcjBpo:b-r7nvki) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L300)):*
> ```Go
> 			fmt.Println("Task created with Title " + t.Name)
> 		}
> 		assigneeTasks.Unlock()
> ```

You are holding the lock for too long. There is a POST request there too. In this time no other goroutine has access to the map. 
1. Read from the map.
2. Change the map after finding if assignee information needs to be added to it.
3. Release the lock
4. Now make post requests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12)*

**Comment by adishap** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[webhooks/webhooks.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5dA9Q18wmRmQijKrZ:-KX9Lx9tLewuQ0Uuimep:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L35)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> we didn't make these as flags?
</details>
Done.

---

*[webhooks/webhooks.go, line 45 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5dKVFyselTEiJsvAC:-KX9epJ6pOxIBLkhTPuu:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L45)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> so you don't need encapsulation for this. 
> ```
> var (
> mu sync.Mutex
> assigneeMap map[int][]string
> )
> It is obvious when you declare it like this that mu guards assigneeMap.
</details>
Done.

---

*[webhooks/webhooks.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5dTkd_IcwZrYpxARI:-KX9N8MPp9cv7iB12fla:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L47)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Have a comment here that this contains PR no => assignees information.
</details>
Done.

---

*[webhooks/webhooks.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5e1ugQ86nK-TnyQtC:-KX9erbicK_MvPF5iQCy:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L71)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> can just be assigneeMap = make(map[]int[]string)
</details>
Done.

---

*[webhooks/webhooks.go, line 278 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5edo2sLB0QXoLxceF:-KX9NBrMbWH_kYCCmbP-:b-mtr3lv) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L278)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> what is `a.Login`?
</details>
a is for pr.Assignee struct where Login is assignee's github username which is used from `login` in payload data.

---

*[webhooks/webhooks.go, line 284 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5ffOe8Xhc-nVc39Im:-KX9pF1sOOC5WZBfGLQc:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L284)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Move some of this to another function.
> func newTask() *Task {
> }
</details>
Done.

---

*[webhooks/webhooks.go, line 300 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5f5OCQMMGyUkcjBpn:-KX9pHXZ5PAoN0ZuwRf8:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L300)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> You are holding the lock for too long. There is a POST request there too. In this time no other goroutine has access to the map. 
> 1. Read from the map.
> 2. Change the map after finding if assignee information needs to be added to it.
> 3. Release the lock
> 4. Now make post requests.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12)*

**Comment by pawanrawal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[webhooks/webhooks.go, line 278 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5edo2sLB0QXoLxceF:-KXAfi5pHK3EMfY0OJ40:b264d) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L278)):*
<details><summary><i>Previously, adishap (Adisha Porwal) wrote…</i></summary>
> a is for pr.Assignee struct where Login is assignee's github username which is used from `login` in payload data.
</details>
login is a bad name IMHO then.

---

*[webhooks/webhooks.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAdatG7Uk17Rh-Eo7Z:-KXAdatG7Uk17Rh-Eo7_:b-3qp7um) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L54)):*
> ```Go
> 	usernames   = []map[string]string{}
> 	token       = flag.String("token", "", "Auth token provided by Asana")
> 	projectID   = flag.Int64("project", 0, "Asana project ID")
> ```

log.Fatal if this or workspaceID is 0 or invalid?

---

*[webhooks/webhooks.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAdhbYnRbAMUuA_WfQ:-KXAdhbYnRbAMUuA_WfR:b5xn968) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L54)):*
> ```Go
> 	usernames   = []map[string]string{}
> 	token       = flag.String("token", "", "Auth token provided by Asana")
> 	projectID   = flag.Int64("project", 0, "Asana project ID")
> ```

Just int should be fine. No need for int64?

---

*[webhooks/webhooks.go, line 243 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAdqABW1MZu9C5vzKi:-KXAdqABW1MZu9C5vzKj:bjyaczy) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L243)):*
> ```Go
> 
> 	url := convertURL(pr.URL)
> 	t := task{}
> ```

t := task {
  Notes: url,
  Projects: []int64{*projectID},
  Tags : []int{prtag, green, next},
}
is more readable?

---

*[webhooks/webhooks.go, line 261 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAeqvnM3J6sOyyX3K8:-KXAeqvoATYcJKjRr1vz:bdec5qk) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L261)):*
> ```Go
> 
> 		newTask(t)
> 	} else {
> ```

else if taskType == something for a more concise check?

---

*[webhooks/webhooks.go, line 262 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAeziKuQ0hLJQnVgxc:-KXAeziKuQ0hLJQnVgxd:bci8yzv) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L262)):*
> ```Go
> 		newTask(t)
> 	} else {
> 		aList := make(map[string]bool)
> ```

Is this aList for finding members who are not in assigneeMap but in the PR? We can just have a `[]string` for it.

Basically, you go through the assignee list from the payload, check those that are not in assigneeMap, add them to a temp array, also add them to the map and update the map.
Then you iterate through the array and create tasks.

---

*[webhooks/webhooks.go, line 271 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAeImIAwWqD6wDC8Pc:-KXAeImIAwWqD6wDC8Pd:b6dscwh) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L271)):*
> ```Go
> 			}
> 		} else {
> 			assigneeMap[pr.Number] = []string{}
> ```

I don't  think you need this block. Go initializes data types with their zero value already, you could straight away do an append.

---

*[webhooks/webhooks.go, line 351 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAe8YXa0wQNz6LRLOs:-KXAe8YXa0wQNz6LRLOt:b-ff6r0e) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L351)):*
> ```Go
> }
> 
> func newTask(t task) {
> ```

should actually be called createTask, do we have already have something with that name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12)*

**Comment by adishap** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[webhooks/webhooks.go, line 278 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KX5edo2sLB0QXoLxceF:-KXKN4n6HkGJ_kRwhD3A:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/3f5731ec2f25c75f4ec3fc7fd98deb5c7c354007/webhooks/webhooks.go#L278)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> login is a bad name IMHO then.
</details>
Done.

---

*[webhooks/webhooks.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAdhbYnRbAMUuA_WfQ:-KXKJTVxsSFviUGjh9Jr:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L54)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Just int should be fine. No need for int64?
</details>
Done.

---

*[webhooks/webhooks.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAdatG7Uk17Rh-Eo7Z:-KXK_kOq1cTRutXIPnAN:b-dfqlr6) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L54)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> log.Fatal if this or workspaceID is 0 or invalid?
</details>
Shifting task creation to task warrior so not doing it.

---

*[webhooks/webhooks.go, line 243 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAdqABW1MZu9C5vzKi:-KXKL-f9Y1GkX3GBD6Xo:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L243)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> t := task {
>   Notes: url,
>   Projects: []int64{*projectID},
>   Tags : []int{prtag, green, next},
> }
> is more readable?
</details>
Done.

---

*[webhooks/webhooks.go, line 261 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAeqvnM3J6sOyyX3K8:-KXKLAFzlfhhTqZVPkyl:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L261)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> else if taskType == something for a more concise check?
</details>
Done.

---

*[webhooks/webhooks.go, line 262 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAeziKuQ0hLJQnVgxc:-KXKY0bu5TI664kFRjap:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L262)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Is this aList for finding members who are not in assigneeMap but in the PR? We can just have a `[]string` for it.
> 
> Basically, you go through the assignee list from the payload, check those that are not in assigneeMap, add them to a temp array, also add them to the map and update the map.
> Then you iterate through the array and create tasks.
</details>
Done.

---

*[webhooks/webhooks.go, line 271 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAeImIAwWqD6wDC8Pc:-KXKLf8sRTrPJeA4ZvDW:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L271)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I don't  think you need this block. Go initializes data types with their zero value already, you could straight away do an append.
</details>
Done.

---

*[webhooks/webhooks.go, line 351 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXAe8YXa0wQNz6LRLOs:-KXKN7VDKc9zcHmLtnJ5:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/29a76b105fdc2ef1482c20415a5d5b82cdc505d4/webhooks/webhooks.go#L351)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> should actually be called createTask, do we have already have something with that name?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12)*

**Comment by pawanrawal** [comment]
one small thing, we can submit then.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[webhooks/webhooks.go, line 266 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXKexkRJWG5Gl_oyyf5:-KXKexkSOFt6yDMZzkG_:b9q107j) ([raw file](https://github.com/dgraph-io/perf/blob/450f5cd99f0e94609a2992974773da5b7d4f6960/webhooks/webhooks.go#L266)):*
> ```Go
> 
> 		for _, prAssignee := range pr.Assignees {
> 			exists := false
> ```

Write a method like http://stackoverflow.com/questions/15323767/does-golang-have-if-x-in-construct-similar-to-python.

then do 
if !stringInSlice(prAssignee.Username, assigneeMap[pr.Number]) {
  aList = append(aList, prAssignee.Username)
  assigneeMap[pr.Number] = append(assigneeMap[pr.Number], prAssignee.Username)
}

I don't think you need to check if PR exists in Map, if you directly try to append values to it, it should still work. Verify this though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12#-:-KXKfM_j041tO0QboaT3:byxy081)*

**Comment by adishap** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[webhooks/webhooks.go, line 266 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/12#-KXKexkRJWG5Gl_oyyf5:-KXKlm0lpM8Kb81i2S_j:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/450f5cd99f0e94609a2992974773da5b7d4f6960/webhooks/webhooks.go#L266)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Write a method like http://stackoverflow.com/questions/15323767/does-golang-have-if-x-in-construct-similar-to-python.
> 
> then do 
> if !stringInSlice(prAssignee.Username, assigneeMap[pr.Number]) {
>   aList = append(aList, prAssignee.Username)
>   assigneeMap[pr.Number] = append(assigneeMap[pr.Number], prAssignee.Username)
> }
> 
> I don't think you need to check if PR exists in Map, if you directly try to append values to it, it should still work. Verify this though.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12)*

**Comment by pawanrawal** [comment]
:lgtm: thanks for doing the iterations.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/12#-:-KXL6daXYib8mKIUQh6H:b4eunxd)*

**Pull request merged**
