### PR TITLE
Feature/integrate pull requests

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/7)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 8 files reviewed at latest revision, 18 unresolved discussions.

---

*[main.go, line 16 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFhrU2ewoUoN_KRRX4:-KUFhrU32ASHNF3xSBld:bwh56d1) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L16)):*
> ```Go
> )
> 
> const intervalPeriod time.Duration = 24 * time.Hour
> ```

Can just be called interval?

---

*[main.go, line 39 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFiOTvYv_A0eXO0Z1H:-KUFiOTvYv_A0eXO0Z1I:b7m8s3s) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L39)):*
> ```Go
> }
> 
> func updateTicker() *time.Ticker {
> ```

So you want to start updating the Database  at 11 pm IST and then do it once every 24 hours. There has to be a better way to do this.

Maybe something along http://stackoverflow.com/questions/36689774/dynamically-change-ticker-interval.

So initially say you poll every 5 sec, whenever time.Now() > 11 pm IST, you can change the interval to 24 hours.

---

*[main.go, line 40 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFjwylfXE38XgILaG8:-KUFjwymAPH73epjrVCB:b-kjwie2) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L40)):*
> ```Go
> 
> func updateTicker() *time.Ticker {
> 	nextTick := time.Date(time.Now().Year(), time.Now().Month(), time.Now().Day(), 23, 0, 0, 0, time.Local)
> ```

Instead of time.Local better have time.IST? Because, time.Local would be different on different machines?

---

*[main.go, line 52 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFiXct80EtPJrhxEoW:-KUFiXct80EtPJrhxEoX:b-2yqaev) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L52)):*
> ```Go
> 	for {
> 		<-ticker.C
> 		fmt.Println()
> ```

We can delete this?

---

*[main.go, line 58 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFiect-OwBdxEyC4JM:-KUFiecuqHtGBnNPBk3Q:b-wy7fzs) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L58)):*
> ```Go
> 			log.Fatal(err)
> 		}
> 		ticker = updateTicker()
> ```

I think there is a cleaner way of doing this.

---

*[usernames.json, line 1 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlDpj4fsIMfsE3s2z:-KUFlDpj4fsIMfsE3s3-:b7h9e26) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/usernames.json#L1)):*
> ```JSON
> [{ "github_username": "adishap",
> ```

Can probably just be 
[ 
  {
    "github": "adishap",
    "asana": "porwaladisha@gmail.com"
  }
]

---

*[dashboard/dashboard.go, line 19 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlRL-zMD-Dp4LKVhi:-KUFlRL00L-LBvFZu1wk:b5v6ijb) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/dashboard/dashboard.go#L19)):*
> ```Go
> // Dashboard returns template for user dashboard
> func Dashboard(w http.ResponseWriter, r *http.Request) {
> 	t, _ := template.ParseFiles("app/dashboard.html")
> ```

Always handle errors.

---

*[dashboard/dashboard.go, line 55 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlYFGlyjqz9WYgdT9:-KUFlYFGlyjqz9WYgdTA:bqrkm9q) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/dashboard/dashboard.go#L55)):*
> ```Go
> func IncompleteTasks(w http.ResponseWriter, r *http.Request) {
> 	tasks := []x.WarriorTask{}
> 	if r.Method == "OPTIONS" {
> ```

I want you to check a way to write a middleware without using any library, using which you can move this and line and setting Content-Type to a common function.

Its possible using https://github.com/urfave/negroni, but writing something of your own would be a good learning exercise.

---

*[dashboard/dashboard.go, line 91 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlz5Gjbg8-mCeWyAJ:-KUFlz5Gjbg8-mCeWyAK:b8vrxsc) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/dashboard/dashboard.go#L91)):*
> ```Go
> 	}
> 	if !verify {
> 		err = errors.New("Invalid user!")
> ```

What are we doing this error. Shouldn't we return something to the user?

---

*[pullrequests/pullrequests.go, line 43 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFnEBYoZMJl9RhUERm:-KUFnEBYoZMJl9RhUERn:b6mssaz) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L43)):*
> ```Go
> 
> func getPRtasks() ([]task, error) {
> 	fmt.Println("Fetching existing pull request tasks.")
> ```

Why do we need to fetch existing PR tasks? 
Don't we just create tasks on Asana and then the user manages them?

---

*[pullrequests/pullrequests.go, line 69 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFn92-DJNwj012_orT:-KUFn9207FsxJL5UwIpt:b-52z8wh) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L69)):*
> ```Go
> 
> func getTag(tagName string) (Tag, error) {
> 	fmt.Println("Fetiching tag ", tagName)
> ```

Spelling.

---

*[pullrequests/pullrequests.go, line 90 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFoU5sHHsHWCy2VsY8:-KUFoU5t7c7cxQ5XqwTN:bxf7f6t) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L90)):*
> ```Go
> 	fmt.Println("Tag ", tagName, " not found.")
> 
> 	type newtag struct {
> ```

l structs outside functions

---

*[pullrequests/pullrequests.go, line 152 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFnUc65zvKxUJikxSD:-KUFnUc65zvKxUJikxSE:bnepm0k) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L152)):*
> ```Go
> 	}
> 
> 	var temp struct {
> ```

All structs outside functions.

---

*[pullrequests/pullrequests.go, line 181 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFmoZlVgWBrVKzDM7L:-KUFmoZm0ZKnXYq3favl:b-zaaaew) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L181)):*
> ```Go
> // PayloadHandler for incoming webhook that is triggered when a PR is created/modified.
> func PayloadHandler(w http.ResponseWriter, r *http.Request) {
> 	fmt.Println("Data received at /payload")
> ```

Try using a simple logger which shows you what endpoint was hit for your http server. Then you'd get this info for all endpoints.

---

*[pullrequests/pullrequests.go, line 184 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFmwaf9xonCzyoAa9E:-KUFmwaf9xonCzyoAa9F:bmbg67j) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L184)):*
> ```Go
> 	decoder := json.NewDecoder(r.Body)
> 
> 	type data struct {
> ```

Hmm, these structs should be defined outside the function.

---

*[pullrequests/pullrequests.go, line 219 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFnsIvi8ZUFabLdx2f:-KUFnsIw91i11Pt-xWt_:b-v2cb85) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L219)):*
> ```Go
> 		t.Projects = []int64{projectID}
> 		t.Assignee = assignee
> 		t.Tags = []int{prtag.ID, greentag.ID, nexttag.ID}
> ```

Not possible to create a task with tag names?
Might be better to have a `tag` type. Then these can just of that type and have name pr, green, next.

---

*[pullrequests/pullrequests.go, line 241 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFoG-cVgv1vtCtYvX2:-KUFoG-cVgv1vtCtYvX3:b-eiqi2x) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L241)):*
> ```Go
> }
> 
> func getUserEmail(githubLogin string) (string, error) {
> ```

This should happen when the program is loaded and not again and again whenever there is an PR event because this doesn't change right?

---

*[syncDB/syncDB.go, line 1 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFmOl-2SZ3GmQ3QjIp:-KUFmOl-2SZ3GmQ3QjIq:b-oxb3lc) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/syncDB/syncDB.go#L1)):*
> ```Go
> package main
> ```

Btw this reminds we all the files should have a Copyright and does this project have a LICENSE? Add that too.

E.g. for copyright https://github.com/dgraph-io/dgraph/blob/master/algo/doc.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7)*

**Comment by adishap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 18 unresolved discussions.

---

*[main.go, line 16 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFhrU2ewoUoN_KRRX4:-KUGCErSdfyqkLMRJGQh:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L16)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Can just be called interval?
</details>
Done.

---

*[main.go, line 39 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFiOTvYv_A0eXO0Z1H:-KUGZdaxqAKCyt2rzRI8:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L39)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> So you want to start updating the Database  at 11 pm IST and then do it once every 24 hours. There has to be a better way to do this.
> 
> Maybe something along http://stackoverflow.com/questions/36689774/dynamically-change-ticker-interval.
> 
> So initially say you poll every 5 sec, whenever time.Now() > 11 pm IST, you can change the interval to 24 hours.
</details>
Done.

---

*[main.go, line 40 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFjwylfXE38XgILaG8:-KUGCfgTuc71uJdqk8Sf:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L40)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Instead of time.Local better have time.IST? Because, time.Local would be different on different machines?
</details>
Done.

---

*[main.go, line 52 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFiXct80EtPJrhxEoW:-KUGZkmYpGNBLaITZchD:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L52)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We can delete this?
</details>
Done.

---

*[main.go, line 58 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFiect-OwBdxEyC4JM:-KUGZn10no1evoE-pXzH:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/main.go#L58)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I think there is a cleaner way of doing this.
</details>
Done.

---

*[usernames.json, line 1 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlDpj4fsIMfsE3s2z:-KUGCtuVeJKWVl-Ubk7Q:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/usernames.json#L1)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Can probably just be 
> [ 
>   {
>     "github": "adishap",
>     "asana": "porwaladisha@gmail.com"
>   }
> ]
</details>
Done.

---

*[dashboard/dashboard.go, line 19 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlRL-zMD-Dp4LKVhi:-KUGDLnTojbiRPirg7IM:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/dashboard/dashboard.go#L19)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Always handle errors.
</details>
Done.

---

*[dashboard/dashboard.go, line 55 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlYFGlyjqz9WYgdT9:-KUH5B0SEcdjoia6QJ6D:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/dashboard/dashboard.go#L55)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I want you to check a way to write a middleware without using any library, using which you can move this and line and setting Content-Type to a common function.
> 
> Its possible using https://github.com/urfave/negroni, but writing something of your own would be a good learning exercise.
</details>
Done.

---

*[dashboard/dashboard.go, line 91 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFlz5Gjbg8-mCeWyAJ:-KUGc7qMfiPmmlgXenwp:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/dashboard/dashboard.go#L91)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> What are we doing this error. Shouldn't we return something to the user?
</details>
Done.

---

*[pullrequests/pullrequests.go, line 43 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFnEBYoZMJl9RhUERm:-KUG_QzJPzo3NkAU15dK:bbsqnyo) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L43)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Why do we need to fetch existing PR tasks? 
> Don't we just create tasks on Asana and then the user manages them?
</details>
Done.
Removed it. Create that function to provide functionality to update tasks but we are not implemnting it now so removed it.

---

*[pullrequests/pullrequests.go, line 69 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFn92-DJNwj012_orT:-KUG_JFVqXrgYudIyMcJ:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L69)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Spelling.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 90 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFoU5sHHsHWCy2VsY8:-KUGhzCOSwpe2lPcNa64:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L90)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> l structs outside functions
</details>
Done.

---

*[pullrequests/pullrequests.go, line 152 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFnUc65zvKxUJikxSD:-KUGhx-hEoSEwTyGmS2j:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L152)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> All structs outside functions.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 181 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFmoZlVgWBrVKzDM7L:-KUGi4P_pOpSybOqu_l4:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L181)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Try using a simple logger which shows you what endpoint was hit for your http server. Then you'd get this info for all endpoints.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 184 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFmwaf9xonCzyoAa9E:-KUGi5g3bRCdmBrDtIzC:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L184)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, these structs should be defined outside the function.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 219 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFnsIvi8ZUFabLdx2f:-KUGkkqaGe2gX7irFqJu:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L219)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Not possible to create a task with tag names?
> Might be better to have a `tag` type. Then these can just of that type and have name pr, green, next.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 241 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFoG-cVgv1vtCtYvX2:-KUGxTOq5uUn1zCZVVZZ:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/pullrequests/pullrequests.go#L241)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This should happen when the program is loaded and not again and again whenever there is an PR event because this doesn't change right?
</details>
Done.

---

*[syncDB/syncDB.go, line 1 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUFmOl-2SZ3GmQ3QjIp:-KUGokKOq-DvBAzZQ1GO:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/fc79eb40c2f4b084bb040ad01520b239d10288ba/syncDB/syncDB.go#L1)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Btw this reminds we all the files should have a Copyright and does this project have a LICENSE? Add that too.
> 
> E.g. for copyright https://github.com/dgraph-io/dgraph/blob/master/algo/doc.go
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7)*

**Comment by pawanrawal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[pullrequests/pullrequests.go, line 207 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHG_PdRKYESZGW6cgO:-KUHG_PdRKYESZGW6cgP:b-qltmax) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L207)):*
> ```Go
> func createTask(taskType string, pr PullRequest) {
> 	t := task{}
> 	prtag, _ := getTag("pullrequest")
> ```

The bad thing here is that to get ids of these three tags. You make the API call to get all tags everytime. So avoid that otherwise your program would be slow.

---

*[pullrequests/pullrequests.go, line 245 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHGtEjeRR8e_kfnj-E:-KUHGtEjeRR8e_kfnj-F:b-xg0nb3) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L245)):*
> ```Go
> func getUserEmail(githubLogin string) (string, error) {
> 	if len(usernames) == 0 {
> 		fmt.Println("Reading usrnames from JSON file.")
> ```

Ideally this  reading of the file should just happen in a package level init() function.

---

*[pullrequests/pullrequests.go, line 245 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHH3CyaF_2cY924oX_:-KUHH3CyaF_2cY924oXa:b123idb) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L245)):*
> ```Go
> func getUserEmail(githubLogin string) (string, error) {
> 	if len(usernames) == 0 {
> 		fmt.Println("Reading usrnames from JSON file.")
> ```

spelling

---

*[pullrequests/pullrequests.go, line 261 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHH1usa9Du68AciFiK:-KUHH1ut35caDOAgEaf7:b123idb) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L261)):*
> ```Go
> 		}
> 	}
> 	err := errors.New("Username not avialable.")
> ```

spelling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7)*

**Comment by adishap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[pullrequests/pullrequests.go, line 207 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHG_PdRKYESZGW6cgO:-KUHQIqx72ypOygnGW2b:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L207)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> The bad thing here is that to get ids of these three tags. You make the API call to get all tags everytime. So avoid that otherwise your program would be slow.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 245 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHH3CyaF_2cY924oX_:-KUHKkaAymiXpmbebyf7:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L245)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> spelling
</details>
Done.

---

*[pullrequests/pullrequests.go, line 245 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHGtEjeRR8e_kfnj-E:-KUHQKRuYq6xbkS4PhCx:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L245)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Ideally this  reading of the file should just happen in a package level init() function.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 261 at r5](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHH1usa9Du68AciFiK:-KUHKxeQ5-bqrR2jwqG8:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/e11c7514dafbc1629fb388980dfeeb2288d94ded/pullrequests/pullrequests.go#L261)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> spelling
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7)*

**Comment by pawanrawal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[pullrequests/pullrequests.go, line 105 at r6](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHXX6_WQEdepQJYt7y:-KUHXX6ahXC_7i15PQrB:b1akn5d) ([raw file](https://github.com/dgraph-io/perf/blob/7b8ab09054083f6d24200c909e0ca415e9e1b3b4/pullrequests/pullrequests.go#L105)):*
> ```Go
> 
> func getTagID(tagName string) (int, error) {
> 	if len(tags) == 0 {
> ```

This check isn't required. 
We would be calling getTags() everytime before getTagId() calls.

---

*[pullrequests/pullrequests.go, line 120 at r6](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHXu-rjhRlf0xlUz9K:-KUHXu-rjhRlf0xlUz9L:bxj6ipy) ([raw file](https://github.com/dgraph-io/perf/blob/7b8ab09054083f6d24200c909e0ca415e9e1b3b4/pullrequests/pullrequests.go#L120)):*
> ```Go
> 	fmt.Println("Tag ", tagName, " not found.")
> 
> 	t := Tag{
> ```

Hmm, we shouldn't be creating tags from here. They should already be there. They are fixed, aren't they?

---

*[pullrequests/pullrequests.go, line 233 at r6](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHXiYie1ZFwxpS1Bhk:-KUHXiYie1ZFwxpS1Bhl:bsvw0ui) ([raw file](https://github.com/dgraph-io/perf/blob/7b8ab09054083f6d24200c909e0ca415e9e1b3b4/pullrequests/pullrequests.go#L233)):*
> ```Go
> func createTask(taskType string, pr PullRequest) {
> 	t := task{}
> 	green, _ := getTagID("green")
> ```

getTags() before the first request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7)*

**Comment by adishap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[pullrequests/pullrequests.go, line 105 at r6](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHXX6_WQEdepQJYt7y:-KUHgxteyzBMMXhpfgjn:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/7b8ab09054083f6d24200c909e0ca415e9e1b3b4/pullrequests/pullrequests.go#L105)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This check isn't required. 
> We would be calling getTags() everytime before getTagId() calls.
</details>
Done.

---

*[pullrequests/pullrequests.go, line 120 at r6](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHXu-rjhRlf0xlUz9K:-KUHgqv1soJ-rcYotWSQ:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/7b8ab09054083f6d24200c909e0ca415e9e1b3b4/pullrequests/pullrequests.go#L120)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, we shouldn't be creating tags from here. They should already be there. They are fixed, aren't they?
</details>
Done.

---

*[pullrequests/pullrequests.go, line 233 at r6](https://reviewable.io:443/reviews/dgraph-io/perf/7#-KUHXiYie1ZFwxpS1Bhk:-KUHgt57oSW3gsBQJftH:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/7b8ab09054083f6d24200c909e0ca415e9e1b3b4/pullrequests/pullrequests.go#L233)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> getTags() before the first request.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/7#-:-KUHvi7lkTQYzP4z_nv-:bnfp4nl)*

**Pull request merged**
