### PR TITLE
Feature/authenticate

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/9)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[oauth2_proxy.cfg, line 3 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdn1rxUcDuyet7vg9P:-KVdn1ryghf0-ebKLYw7:b-iqse7w) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/oauth2_proxy.cfg#L3)):*
> ```INI
> provider = "github"
> # add github_org for which you want to authorize
> github_org = "<github_org>"
> ```

dgraph-io

---

*[oauth2_proxy.cfg, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdnSQ3pdu-o2TWqTFQ:-KVdnSQ3pdu-o2TWqTFR:b-mony8v) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/oauth2_proxy.cfg#L5)):*
> ```INI
> github_org = "<github_org>"
> skip_provider_button = "true"
> upstreams = ["http://127.0.0.1"]
> ```

We don't want to add port information?

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdnOD0NeajGp9ctNH8:-KVdnOD0NeajGp9ctNH9:b8aiy1w) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/README.md#L22)):*
> ```Markdown
> 
>      ```mysql -u <username> -p perf_db < dump_file_path/perf_db.sql```
> * Install nginx from [here](http://nginx.org/en/download.html)
> ```

We already have nginx.conf, so you can just point them to it.

---

*[dashboard/dashboard.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdoGKDPHBzIrNXxo7B:-KVdoGKDPHBzIrNXxo7C:b7t3wx5) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/dashboard/dashboard.go#L114)):*
> ```Go
> 		users = append(users, user)
> 	} else {
> 		users, err = scores.GetUsers()
> ```

So are the users picked up dynamically now?

---

*[nginx/nginx.conf, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdo9cBAiw3w2Q1hy6S:-KVdo9cBAiw3w2Q1hy6T:b-mqlb32) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/nginx/nginx.conf#L5)):*
> ```Nginx
> pid /run/nginx.pid;
> 
> events {
> ```

Where is the config for https?

---

*[nginx/nginx.conf, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdo08xgXbO_O7GfgKo:-KVdo08xgXbO_O7GfgKp:b-yc731h) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/nginx/nginx.conf#L50)):*
> ```Nginx
>   # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
> 
>   ##
> ```

Lets just delete all this commented stuff.

---

*[nginx/nginx.conf, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdo2ng2MgNZMxz6vdW:-KVdo2ng2MgNZMxz6vdX:b-7u8ezk) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/nginx/nginx.conf#L76)):*
> ```Nginx
> 
> 
> #mail {
> ```

delete this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/9)*

**Comment by adishap** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[oauth2_proxy.cfg, line 3 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdn1rxUcDuyet7vg9P:-KVe0YFKDiiQaoi76YMU:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/oauth2_proxy.cfg#L3)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> dgraph-io
</details>
Done.

---

*[oauth2_proxy.cfg, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdnSQ3pdu-o2TWqTFQ:-KVe0nrm3HvNHH1116mq:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/oauth2_proxy.cfg#L5)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We don't want to add port information?
</details>
Done.

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdnOD0NeajGp9ctNH8:-KVe129r5S6oZGHgKyHi:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/README.md#L22)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We already have nginx.conf, so you can just point them to it.
</details>
Done.

---

*[dashboard/dashboard.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdoGKDPHBzIrNXxo7B:-KVe1EX40xtNLav318Lr:b-x29be9) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/dashboard/dashboard.go#L114)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> So are the users picked up dynamically now?
</details>
So this change is for score chart when the user name is not provided it will give data for all the users else it will give data for that particular user.

---

*[nginx/nginx.conf, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdo9cBAiw3w2Q1hy6S:-KVe1A9bIDPOstwUF-oi:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/nginx/nginx.conf#L5)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Where is the config for https?
</details>
Done.

---

*[nginx/nginx.conf, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdo08xgXbO_O7GfgKo:-KVe1833RrqtY1WuqsUd:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/nginx/nginx.conf#L50)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Lets just delete all this commented stuff.
</details>
Done.

---

*[nginx/nginx.conf, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVdo2ng2MgNZMxz6vdW:-KVe18f_NFwFKC3W1Yxo:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/de6d074880c434bc8eb34a795dc7cd4fa653e74e/nginx/nginx.conf#L76)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> delete this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/9)*

**Comment by pawanrawal** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[oauth2_proxy.cfg, line 10 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KViKHhxibP9QGxu-niP:-KViKHhyrhEVHbDeUHNR:basrfmw) ([raw file](https://github.com/dgraph-io/perf/blob/a3cb7b6419ff9544eb60d35b8248bf678da668ca/oauth2_proxy.cfg#L10)):*
> ```INI
> client_id = "<client_id>"
> # add client secret
> client_secret = "<client_secret>"
> ```

A good way usually would be to pick these up from bash environment variables instead of you editing this file on the server.

---

*[nginx/nginx.conf, line 11 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KViLjN8vh3ivmJzAwAk:-KViLjN8vh3ivmJzAwAl:b7rrgw5) ([raw file](https://github.com/dgraph-io/perf/blob/a3cb7b6419ff9544eb60d35b8248bf678da668ca/nginx/nginx.conf#L11)):*
> ```Nginx
> 
>     ssl_certificate /path/to/certificate.crt;
>     ssl_certificate_key /path/to/certificate.key;
> ```

have the actual path here it's not sensitive info.

---

*[scores/scores.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KViLuqX18It1jX-OW6j:-KViLuqX18It1jX-OW6k:b-mx8ns6) ([raw file](https://github.com/dgraph-io/perf/blob/a3cb7b6419ff9544eb60d35b8248bf678da668ca/scores/scores.go#L318)):*
> ```Go
> 	}
> 	// update scores in database if scores are calculated for a week
> 	if days == 6 {
> ```

not 7?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/9)*

**Comment by adishap** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[oauth2_proxy.cfg, line 10 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KViKHhxibP9QGxu-niP:-KVicfNhQrXKUWEc5Eli:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a3cb7b6419ff9544eb60d35b8248bf678da668ca/oauth2_proxy.cfg#L10)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> A good way usually would be to pick these up from bash environment variables instead of you editing this file on the server.
</details>
Done.

---

*[nginx/nginx.conf, line 11 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KViLjN8vh3ivmJzAwAk:-KVicgh22iTOug3jpNLo:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a3cb7b6419ff9544eb60d35b8248bf678da668ca/nginx/nginx.conf#L11)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> have the actual path here it's not sensitive info.
</details>
Done.

---

*[scores/scores.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KViLuqX18It1jX-OW6j:-KViSrpd_Uj3qTt3wXX-:b-elzhxy) ([raw file](https://github.com/dgraph-io/perf/blob/a3cb7b6419ff9544eb60d35b8248bf678da668ca/scores/scores.go#L318)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> not 7?
</details>
I pass n-1 days for having data for  n days as total no of days will become n because it also involves current date data also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/9)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 88 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVxMibIhXShfM6XXG42:-KVxMibIhXShfM6XXG43:bfytf8q) ([raw file](https://github.com/dgraph-io/perf/blob/9d59c62192956dbf5043dbfd9f93571f0edf8f35/main.go#L88)):*
> ```Go
> 	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> 		handler.ServeHTTP(w, r)
> 		log.Println(r.Method, r.URL.Path, time.Since(start))
> ```

So you don't log the time the request was received at but time.Since?

---

*[scores/scores.go, line 506 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVxN5SDpHso0gzirKcM:-KVxN5SEN8xX-IjoNADf:bx0vmed) ([raw file](https://github.com/dgraph-io/perf/blob/9d59c62192956dbf5043dbfd9f93571f0edf8f35/scores/scores.go#L506)):*
> ```Go
> 
> // Middleware to set content header json and check if r.Method is not options
> func Middleware(w http.ResponseWriter, r *http.Request) {
> ```

I am sure there would be a generic way to add this middleware to all requests. Maybe check that later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/9#-:-KVjAVLXFqBGeWBB4-Tc:bnfp4nl)*

**Comment by adishap** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 88 at r3](https://reviewable.io:443/reviews/dgraph-io/perf/9#-KVxMibIhXShfM6XXG42:-KVxNnRYOUxXbe2G3Spt:bgh44i4) ([raw file](https://github.com/dgraph-io/perf/blob/9d59c62192956dbf5043dbfd9f93571f0edf8f35/main.go#L88)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> So you don't log the time the request was received at but time.Since?
</details>
I was logging how much time it took to complete the request.Added timewhen request was recieved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/9)*

**Pull request merged**
