### PR TITLE
Show score calculation

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/perf/14)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[main.go, line 44 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL6lwkvrKPV28ip-zf:-KXL6lwkvrKPV28ip-zg:b2508jh) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/main.go#L44)):*
> ```Go
> 	http.HandleFunc("/getScore", scores.GetScoreHandler)
> 	http.HandleFunc("/", scores.Score)
> 	http.HandleFunc("/score/showCalculation", scores.ShowCalculation)
> ```

/score/calculation?

---

*[scores/scores.go, line 410 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8CioK7CtgPMGdrlj:-KXL8CioK7CtgPMGdrlk:btvqmyj) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L410)):*
> ```Go
> 
> 	user := r.FormValue("user")
> 	days, err := strconv.Atoi(r.FormValue("days"))
> ```

you don't send an integer from the frontend?

---

*[scores/scores.go, line 428 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL7ChJ0koA7vI76gkJ:-KXL7ChJ0koA7vI76gkK:bfc0msz) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L428)):*
> ```Go
> 
> 	for _, color := range colors {
> 		learningTags[color] = 0
> ```

not needed, Go types have a default zero value. you don't to initialize stuff with 0.

---

*[scores/scores.go, line 436 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL7j__9aqtXRGCvhRz:-KXL7j__9aqtXRGCvhS-:bap70g8) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L436)):*
> ```Go
> 			// for learning project
> 			if task.Project == learningProject {
> 				if tag == "red" {
> ```

have a switch case here.

---

*[scores/scores.go, line 477 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8K0hNNOT4tHU1xGr:-KXL8K0hNNOT4tHU1xGs:b70zwff) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L477)):*
> ```Go
> 	for i := 0; i < days; i++ {
> 		t := time.Now().AddDate(0, 0, -i)
> 		if t.Weekday() == time.Sunday || t.Weekday() == time.Saturday {
> ```

I saw this stuff somewhere else today? Is this code repeated? Can we abstract it out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/14)*

**Comment by adishap** [comment]
Review status: 4 of 7 files reviewed at latest revision, 16 unresolved discussions.

---

*[main.go, line 44 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL6lwkvrKPV28ip-zf:-KXOa6l4qnMTnXZv_Sht:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/main.go#L44)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> /score/calculation?
</details>
Done.

---

*[app/assets/js/scores.js, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryya-r1-27:-KXOa80CWXmkpwD0H6Bn:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/app/assets/js/scores.js#L27)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> Missing semicolon.
</details>
Done.

---

*[app/assets/js/scores.js, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryya-r1-52:-KXOa9IWQ0so2xxIsh2V:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/app/assets/js/scores.js#L52)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> Missing semicolon.
</details>
Done.

---

*[app/assets/js/scores.js, line 158 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryya-r1-158:-KXOaACI696S8oAO7wd7:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/app/assets/js/scores.js#L158)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> Missing semicolon.
</details>
Done.

---

*[app/assets/js/scores.js, line 159 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryya-r1-159:-KXOaBHrmtCwTqitP383:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/app/assets/js/scores.js#L159)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> Missing semicolon.
</details>
Done.

---

*[scores/scores.go, line 437 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-437:-KXOdZsTCjV5DmkgwUvP:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L437)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace learningTags["red"] += 1 with learningTags["red"]++
</details>
Done.

---

*[scores/scores.go, line 440 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-440:-KXOdaIFiZf6ahXN9WEg:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L440)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace learningTags["green"] += 1 with learningTags["green"]++
</details>
Done.

---

*[scores/scores.go, line 443 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-443:-KXOdbKwSbLmtIfjcjyk:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L443)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace learningTags["blue"] += 1 with learningTags["blue"]++
</details>
Done.

---

*[scores/scores.go, line 446 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-446:-KXOdcPabOIgeTMXipzY:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L446)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace learningTags["black"] += 1 with learningTags["black"]++
</details>
Done.

---

*[scores/scores.go, line 451 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-451:-KXOddMPj1_-y9w5GWC0:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L451)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace otherTags["red"] += 1 with otherTags["red"]++
</details>
Done.

---

*[scores/scores.go, line 454 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-454:-KXOdeX641D2XPXEc3M8:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L454)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace otherTags["green"] += 1 with otherTags["green"]++
</details>
Done.

---

*[scores/scores.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXKxw95L3UuKwxmryye-r1-457:-KXOdf_7cInJPHAQ-0pS:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/789a6687212307d533c7a438af367610cdf1c4c3/scores/scores.go#L457)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should replace otherTags["blue"] += 1 with otherTags["blue"]++
</details>
Done.

---

*[scores/scores.go, line 410 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8CioK7CtgPMGdrlj:-KXOblYZIhR92PSO6Es-:b-138in) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L410)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> you don't send an integer from the frontend?
</details>
I send a integer only still it requires to convert it into integer.

---

*[scores/scores.go, line 428 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL7ChJ0koA7vI76gkJ:-KXOcVsg1W5Gy2LQfLjR:b1esq5m) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L428)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> not needed, Go types have a default zero value. you don't to initialize stuff with 0.
</details>
If we dont do this it will only initatialize for the the tags which are for users it will not intialize for all the colors in learningTags and otherTags.

---

*[scores/scores.go, line 436 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL7j__9aqtXRGCvhRz:-KXOdZ9cO1cJpkIUvIbG:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L436)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> have a switch case here.
</details>
Done.

---

*[scores/scores.go, line 477 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8K0hNNOT4tHU1xGr:-KXOgRhur7DmvrctpY-Z:b-66drkp) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L477)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I saw this stuff somewhere else today? Is this code repeated? Can we abstract it out?
</details>
In this loop is similar to calculatePresence function but but they dont perform same tasks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/14)*

**Comment by pawanrawal** [comment]
:lgtm: minor things after that we can merge this.

---

Review status: 4 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[scores/scores.go, line 410 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8CioK7CtgPMGdrlj:-KXPXd7knerATY97xN9v:bs7kfta) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L410)):*
<details><summary><i>Previously, adishap (Adisha Porwal) wrote…</i></summary>
> I send a integer only still it requires to convert it into integer.
</details>
That shouldn't be so I think, maybe figure this out later.

---

*[scores/scores.go, line 428 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL7ChJ0koA7vI76gkJ:-KXPXurLsgUqDEyWz8Vw:b-56w2ge) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L428)):*
<details><summary><i>Previously, adishap (Adisha Porwal) wrote…</i></summary>
> If we dont do this it will only initatialize for the the tags which are for users it will not intialize for all the colors in learningTags and otherTags.
</details>
What I am saying is that you dont need to do that, you can straight away do a ++
See this https://play.golang.org/p/WTUUnL3VhP

---

*[scores/scores.go, line 477 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8K0hNNOT4tHU1xGr:-KXPYRCqIERb4zUUCkWB:b-g99jvc) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L477)):*
<details><summary><i>Previously, adishap (Adisha Porwal) wrote…</i></summary>
> In this loop is similar to calculatePresence function but but they dont perform same tasks.
</details>
Ok, if its same we should abstract it otherwise its ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/14#-:-KXPYX87DYjf7F4RtJ0v:bf8zzne)*

**Comment by adishap** [comment]
Review status: 3 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[scores/scores.go, line 410 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8CioK7CtgPMGdrlj:-KXPdJ1fijXGZW569Aw4:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L410)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> That shouldn't be so I think, maybe figure this out later.
</details>
Done.

---

*[scores/scores.go, line 428 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL7ChJ0koA7vI76gkJ:-KXQ-xLgK1lLi1M2DBUz:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L428)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> What I am saying is that you dont need to do that, you can straight away do a ++
> See this https://play.golang.org/p/WTUUnL3VhP
</details>
Done.

---

*[scores/scores.go, line 477 at r2](https://reviewable.io:443/reviews/dgraph-io/perf/14#-KXL8K0hNNOT4tHU1xGr:-KXPdvazJ4ec6K7aqqlx:b-896fix) ([raw file](https://github.com/dgraph-io/perf/blob/a7027fb2e87b7af5bd5167e12c1c305949db2e95/scores/scores.go#L477)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Ok, if its same we should abstract it otherwise its ok.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/perf/14)*

**Pull request merged**
